### ISSUE TITLE
We want to drop the entire fourth and ADD_YOUR_ROW_NUMBER_HERE row

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#113]
05-data-structures-part2 has

> We now know how to add rows and columns to our data.frame in R - but in our work we’ve accidentally added a garbage row. We can ask for a data.frame minus this offender:
>
> ~~~
> cats[-4,]
> ~~~
>
> ~~~
>            coat weight likes_string age
> 1        calico    2.1         TRUE   4
> 2         black    5.0        FALSE   5
> 3         tabby    3.2         TRUE   8
> 5 tortoiseshell    3.3         TRUE   9
> ~~~
>
> Notice the comma with nothing after it to indicate we want to drop the entire fourth row. 

The lesson doesn't say how to drop one set of lines. [Stackoverflow says](http://stackoverflow.com/a/12328064/1802726) to use

> cats[-c(2, 4),]

so I suggest that (1) we change 

> ~~~
> cats[-4,]
> ~~~

to

> ~~~
> cats[-c(4),]
> ~~~

or add one challenge covering this.

**Comment by naupaka** [comment]
Another good idea. In my opinion, I think `cats[-c(4),]` (vs `cats[-4,]`) seems a little awkward, syntax-wise, even if it points to the general solution for removing a set of lines in a df. But I agree it would be worth adding a quick note on how to remove multiple lines, since this is a common enough need that people would find it useful to be exposed to how to do it.
