### ISSUE TITLE
Create an outline.md with an overview of the lessons in this repo, which to include in a standard SWC workshop, and in what order

### ISSUE THREAD

**Issue by naupaka** [swcarpentry/r-novice-gapminder#12]
There is a ton of great content in this repo. Perhaps a great place to start getting it organized would be an outline.md document that lists the repos, and proposes an order and a core set. Then we can focus on getting these core modules polished and move some of the others in to supplementary or additional materials sections? As discussed in the comments on #10

**Comment by sritchie73** [comment]
Ive had a few interested people contact me about the mozsprint. Would it be helpful for a few of us to iterate over an outline beforehand? I suspect large structural changes might be a bit overwhelming for an individual to tackle.

**Comment by hdashnow** [comment]
Great idea. It would be good to get all the structural changes out of the
way before the sprint starts. Let me know what I can do to help (presumably
comment!).

On Thu, May 28, 2015 at 2:09 PM, Scott Ritchie <notifications@github.com>
wrote:

> Ive had a few interested people contact me about the mozsprint. Would it
> be helpful for a few of us to iterate over an outline beforehand? I suspect
> large structural changes might be a bit overwhelming for an individual to
> tackle.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swcarpentry/r-novice-gapminder/issues/12#issuecomment-106165108>
> .
>



-- 
Harriet Dashnow
BSc, BA, MSc (Bioinformatics), PhD candidate
au.linkedin.com/in/hdashnow

**Comment by naupaka** [comment]
+1

**Comment by gvwilson** [comment]
+100 -- sprints are good for filling in bits and pieces, but very 
frustrating for newcomers if the ground is shifting under their feet.  
If you can rearrange the pieces and file lots of one-line tickets 
describing what you want added or fixed, that will give them something 
concrete to do *and* help them avoid tripping over each other.  (Best 
thing if you have time: file a one-line ticket, then put `FIXME #123: 
description description description` in the doc itself where you want 
the change - the ticket allows the newcomer to claim something, so you 
don't get duplication and frustration, and embedded markers in text are 
easier to write and understand.)

**Comment by aammd** [comment]
I volunteer to write the rough draft! fear not, it will be terrible, lots of room for comments.

**Comment by aammd** [comment]
@gvwilson would you mind spelling out this **FIXME** business a little bit more? or perhaps link to a commit where it was successfully done?

**Comment by mikabr** [comment]
Discussing (from mozzsprint) streamlining the lessons: take my thoughts with a grain of salt, because I’ve never actually run R tutorials, but my intuition is that the most important things to learn are dplyr, tidyr, and ggplot, and the sooner you get to them the better. A lot of the more basic things, like data types, data structures, subsetting, etc, are things you need to know to understand R, but may not need / care about right away if you’re trying to do data analysis.

**Comment by hdashnow** [comment]
Oddly enough, I actually don't have a strong opinion about this. I grew up on base R, so I don't use most of these tools. But from what I've heard, they are great for beginners. I'm all for giving the students a positive first R experience that makes them want to try it out on their own data.
So, I think I agree?

**Comment by sritchie73** [comment]
+1 to @mikabr 's thoughts also.

**Comment by aammd** [comment]
+ 100 to this. the Data Structure stuff is much better when people are already accomplishing cool things. rather than right at the start.

**Comment by naupaka** [comment]
I might move this type of content into the `instructors.md` file instead of a separate `outline.md` file, just keep things consolidated.

**Comment by tomwright01** [comment]
I also learned R before the advent of tools such as ggplot and plyr.
I'm not keen on emphasising dplyr ggplot etc over the basics such as data types. In my opinion the aim of SWC is to teach good programming, not data analysis. While ggplot etc are great tools I feel an understanding of datatyping leads to better code.

I agree excitement and achievement are important motivational factors, while I haven't taught R since PR #89 (I think that's the correct PR), I have great hopes that the new structure of lesson topic 4 (data structures) will enhance the relevance and applicability of this topic.

**Comment by naupaka** [comment]
Closing this since it will be handled by upcoming changes to `instructor.md` files.
