### ISSUE TITLE
Enforce R style

### ISSUE THREAD

**Issue by jrnold** [swcarpentry/r-novice-gapminder#155]
Should all the R code in the lesson follow a style guide, like [Hadley's](http://adv-r.had.co.nz/Style.html)?Lintr could be used to automatically check the `.Rmd` files for most violations.

**Comment by aammd** [comment]
I like the idea in principle -- certainly better formatting is easier to read when reading the .Rmd files. However, I think imposing an actual check is overkill for two reasons. First, because knitr passes all the (printed) R chunks through `formatR`, they are all nicely formatted in the rendered versions anyway (which is, in theory, what learners would be looking at). 

Second, and more importantly, we want the barrier to contributing to these lessons to be as low as possible. As it is, contributions often have merge conflicts or other issues for contributors to modify. I feel like it is enough to ask contributors to correct these, while ignoring (at least in an original PR) any inconsistency in their formatting.

**Comment by jrnold** [comment]
Completely reasonable, and sounds good to me. I had forgotten about `formatR`.
