### ISSUE TITLE
Conversion from R-novice-inflammation

### ISSUE THREAD

**Issue by sritchie73** [swcarpentry/r-novice-gapminder#16]
It looks like a lot of work has been put into the [r-novice-inflammation](https://github.com/swcarpentry/r-novice-inflammation) lessons over the last few months, and they now cover a lot more R-specific material (as opposed to a literal translation of the python materials).

I'm wondering if pulling in those lessons, and replacing the Inflammation data with the gapminder data is a good place to start for paring this material down to a half day workshop? We could then have extra lessons for instructors who want to run R over a full day (e.g. a ggplot2 lesson and knitr lesson).

**Comment by naupaka** [comment]
My sense is that the two lessons have diverged substantially at this point and it probably makes sense to keep them separate. I'd like to close this issue unless there are strong objections. Instructors can always pick and choose which of these lessons they teach (since you're right teaching all of it would take a good deal of time).

**Comment by naupaka** [comment]
I am closing this since I think both sets of lessons have diverged substantially and are on good tracks.
