### ISSUE TITLE
Why are these R files in the fig directory?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/r-novice-gapminder#168]
`make lesson-check` reports:

Unexpected image files: 13-dplyr-generate-figures.R, 14-tidyr-generate-figures.R
but of course, those aren't actually images...

**Comment by fmichonneau** [comment]
they are scripts that generate the diagrams that are found in the dplyr and
the tidyr episodes. I left them where I found them but there might be a
better location for them...

**Comment by gvwilson** [comment]
I guess there's no harm in leaving them there - I've trained the tool 
that looks for missing/unused images to ignore .R.
Thaks,
Greg

**Comment by naupaka** [comment]
2nding @fmichonneau. Those scripts make the figures for those lessons (they are called with `source()` in the dplyr and tidyr lessons) - we thought it would be better to have the images scripted if possible (vs just dropping in something from Illustrator), but we also didn't want to put all the image code in the main lesson bodies because it would be too much and unrelated to what learners needed to see. Is there a better best practice for where this type of thing should go?

**Comment by hdashnow** [comment]
@naupaka you could put it in the lessons, but use knitr chunk options to hide it, like this:

```
{r echo=FALSE} 
```

See: https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf

**Comment by naupaka** [comment]
Hi @hdashnow that would fix the issue for the rendered versions, but we also thought that it would be a lot of extra code for folks contributing to the lessons to read through as well (or for those editing the Rmd directly via GitHub). See the discussion on PR #54. We could always stick the code back in - I think it's a tradeoff between consolidation and readability.

**Comment by naupaka** [comment]
My vote is to keep those files separate for now, since it makes it much easier to read and edit the Rmd files for those lessons. Unless there are strong objections, I'd like to close this issue since @gvwilson's fix should remove the error resulting from `make lesson-check`.
