### ISSUE TITLE
Add "*.html" to .gitignore?

### ISSUE THREAD

**Issue by SamPenrose** [swcarpentry/r-novice-gapminder#17]
Should we add "*.html" to .gitignore? When a core maintainer wanted to add the HTML, they could use "git add -f".

**Comment by naupaka** [comment]
Sounds reasonable. @jdblischak has more experience with these R lesson repos. @jdblischak, any reason why this would be a bad idea? Might make it easier to avoid accidental html inclusion in pull requests, and easy enough to `git add -f *.html`

**Comment by sritchie73** [comment]
How about the intermediate markdown files? We could add *.md to the .gitignore too, under the assumption that most contributors wouldn't be modifying non-top markdown files. (Alternatively we could convert these to R markdown, without code blocks, for simplicity).

**Comment by aammd** [comment]
in contrast, over at [r-novice-inflammation](https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/CONTRIBUTING.md) they simply direct contributors to commit changes to source files (in their case, `.md`)

> 3. When editing lesson pages, you need only commit changes to the Markdown source files.

**Comment by sritchie73** [comment]
That seems odd. Do the topic maintainers then transcribe that to R markdown? That's a non-trivial amount of work.

**Comment by sritchie73** [comment]
Looking at the last few pull requests they merged, contributors are expected to commit changes to the `.Rmd` files. I suspect that their CONTRIBUTING.md is wrong, or out of date.

**Comment by aammd** [comment]
Right. Either way, only the *source* files are changed, not the derived files.  I think they did move from .Rmd to .md.

Either way, I suggest that we follow their lead: commit only changes to .Rmd files.  

What do you guys think?

**Comment by sritchie73** [comment]
I agree with that. We just need to make sure the CONTRIBUTING.md is up to date (relates to Issue #25  and another issue i've opened on the lesson-template repo).

**Comment by hdashnow** [comment]
Agree about adding *.html to .gitignore. Adding *.md could have annoying consequences as this is a pretty common file type to be used for many general notes.

How about moving the lessons to a /lessons directory and then adding lessons/*.md to .gitignore

**Comment by naupaka** [comment]
Can't move to /lessons because of the way the makefile and jekyll and the templates handle the website generation; this is standard across all lesson repos. I think adding `.html` to `.gitignore` might make sense, but I'd like to hear @jdblischak's opinion before making any changes.

**Comment by hdashnow** [comment]
Fair point.

Alternate suggestion (thanks @sritchie73), instead of adding `*.md` to .gitignore, we add `*-*.md` which should just match the lessons, and not others such as CONTRIBUTING.md. It's a bit of a hack, I admit, but better than the alternatives so far.

**Comment by jdblischak** [comment]
I don't think ignoring the html files would cause a problem, but I don't think it will prevent PRs with rendered html. Ignoring html files with .gitignore will only require using `git add -f` for untracked files. Already tracked files can be included in a commit with `git add` or `git commit -a`.

As for the contributing directions, the particulars for the R lessons are explained in the README.

https://github.com/swcarpentry/r-novice-inflammation#contributing

This is due to the lesson template. CONTRIBUTING.md is part of the core [lesson-template](https://github.com/swcarpentry/lesson-template) repo. New changes to the lesson template are merged from this repo into downstream lesson repos like this one. Thus making changes to this file creates the risk of merge conflicts. This is why r-novice-inflammation currently has the awkward solution of having two places with contributing information. This is also why the link to Issues is directed to the issues of lesson-template and not the r-novice issues (the same goes for the [contributing directions for python-novice-inflammation](https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/CONTRIBUTING.md)). Development in lesson-template has slowed down recently, so it may be safe to start making changes to the CONTRIBUTING.md file in downstream repos, but of course new changes are already being [discussed](https://github.com/swcarpentry/lesson-template/issues/242).

**Comment by naupaka** [comment]
Closed via #56
