### ISSUE TITLE
Separate challenge chunks

### ISSUE THREAD

**Issue by sritchie73** [swcarpentry/r-novice-gapminder#21]
For many of the back to back challenges, there is only one {.challenge} markdown block. Clarity would be increased by separating out into a challenge block for each individual challenge. See the end of 01-rstudio-intro.Rmd for an example.

**Comment by karawoo** [comment]
+1

@kbroman wrote an awesome script that pulls out the challenges and makes a slideshow of them so that you can easily put the challenges up on the screen while learners are working on them ([script](https://github.com/karawoo/2015-04-27-wsu/blob/gh-pages/syllabus/slides/grab_challenges.rb) and [makefile](https://github.com/karawoo/2015-04-27-wsu/blob/gh-pages/syllabus/slides/Makefile)); splitting the challenges into separate blocks would also allow people (me) to use this script in future workshops.

**Comment by aammd** [comment]
@sritchie73 here is your challenge-creating script! Still not sure we ought necessarily to do this, since it means either adding another `Makefile` or modifying the existing one, neither of which seems ideal?

**Comment by noamross** [comment]
I actually found I had to concatenate challenges back together so I could put multiple challenge questions up on the screen.  I don't know how everyone's teaching flow works, but when there are back-to-back challenges in the lesson script, I give them all to the students at once.

**Comment by aammd** [comment]
Hi @noamross , could you clarify that? Were you trying to do a slideshow of challenges as @karawoo described?
Also, I believe the question for this issue is how the lesson page should be formatted, not how challenges should be presented to students. I'd prefer not to modify this repo to produce a challenge slideshow automatically; it already has a lot of moving parts.

**Comment by noamross** [comment]
Yes, that's right.  I was producing a slides using Karl's script.  Perhaps the solution is to modify the script rather than the lesson files.  Maybe the script could be linked to in teaching notes or just live in a `misc/` or `extras/` directory.

**Comment by aammd** [comment]
I like the idea of linking to the script which would live somewhere else, in a repo dedicated to the purpose. (Could that even be set up with Travis, to confirm that modifications to the lessons don't break the presentation-making magic?)

**Comment by naupaka** [comment]
I think perhaps it's time to close this issue since the new style framework has changed up how challenges are displayed?
