### ISSUE TITLE
gapminder-FiveYearData.csv is not linked to from the material

### ISSUE THREAD

**Issue by anenadic** [swcarpentry/r-novice-gapminder#220]
It is also expected to be in the top level data directory when it is actually located in _episodes_rmd/data. For example, see settings in  _extras/guide.md:

"[gapminder-data]: https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/data/gapminder-FiveYearData.csv"

**Comment by anenadic** [comment]
Similar to #219

**Comment by andreabedini** [comment]
@tomwright01 @naupaka can we get this sorted soon? `bin/generate_md_episodes.R` seems not to do its job wrt to the data files. Also applies to #219. I can help if you explain to me the situation.

**Comment by naupaka** [comment]
As far as I understand it, it's tricky to get the Rmd paths consistent because of how Jekyll is building the site and how knitr changes the working dir when knitting. The lessons themselves seem to render fine, since the links are correct in those. I just modified the links in `guide.md` with commit 9d85f5c50c so that should be fixed now for both gapminder and gapminder-wide.

**Comment by andreabedini** [comment]
Thanks for the quick reply @naupaka !
