### ISSUE TITLE
Defensive Programming

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#221]
Based on the discussion that I started at http://lists.software-carpentry.org/pipermail/discuss/2016-September/004778.html, can we include on this lesson the two episodes that John Blischak, @jdblischak, wrote Defensive programming with stopifnot
, https://jdblischak.github.io/r-intermediate-altmetrics/23-stopifnot.html, and Testing with testit, https://jdblischak.github.io/r-intermediate-altmetrics/24-testit.html?

**Comment by mkcor** [comment]
Thanks, @rgaiacs .

:+1: to including lesson "Defensive programming with stopifnot" (editing reference to function `sum_calc_stat`). In a context of data analysis, I don't think I would agree with the statement that "it will involve more work" (since that's what you do anyway, you explore the data), but this is Software Carpentry, not Data Carpentry, so I won't argue.

I'm not as motivated to include lesson "Testing with testit" though.  I believe unit testing represents something more advanced (especially in the R world).  Plus it adds a dependency (be it `testit` or `testthat`).  Plus it touches on R packaging (as @lwjohnst86 rightly mentioned in the thread).

**Comment by naupaka** [comment]
I am inclined to agree with @mkcor on this. I think the `stopifnot()` lesson would be a nice and appropriate addition, but I think that the lesson on unit tests might be a bit too much.

**Comment by jdblischak** [comment]
I am defending next week, so I apologize in advance that I won't be able to have an extended discussion about this. Here are my thoughts:

*  I'm glad you liked my lessons! However, I am not sure how useful they will be as compared to just starting from scratch. The majority of the exposition and the examples refer to functions that were built earlier in the lesson.
*  I love using `stopifnot`. When I write code, I aim to take the quick sanity checks that I run in the R console and paste them into a `stopifnot` call. You can see my GitHub repos are [littered with stopifnot](https://github.com/search?o=desc&q=stopifnot+user%3Ajdblischak&ref=searchresults&s=&type=Code&utf8=%E2%9C%93).
*  The [defensive programming lesson][defensive] from [python-novice-inflammation][] did not get translated to [r-novice-inflammation][] for the simple reason that I was not motivated enough to do it. The defensive programming lesson has nothing to do with the previous examples on the inflammation data and is way too advanced for a novice audience (it begins with defining a function that has over 10 lines of code, larger than any function written up to this point in the lesson). I am surprised that the Python maintainers have moved this difficult-to-teach topic in front of [command line programs][cmdline], which actually nicely builds on top of the previous inflammation examples.
*  For R-specific questions, in the future please send them to the [r-discuss][] mailing list. This allows instructors to stay up-to-date with developments in the SWC R community without having to sift through the high-volume discuss list.

[defensive]: http://swcarpentry.github.io/python-novice-inflammation/08-defensive/
[python-novice-inflammation]: http://swcarpentry.github.io/python-novice-inflammation/
[r-novice-inflammation]: http://swcarpentry.github.io/r-novice-inflammation/
[cmdline]: http://swcarpentry.github.io/python-novice-inflammation/10-cmdline/
[r-discuss]: http://lists.software-carpentry.org/listinfo/r-discuss

**Comment by naupaka** [comment]
Just following up on this thread. It seems like the best way forward would be for someone to port the content of @jdblischak's `stopifnot()` lesson into a framework that would fit with the rest of the gapminder lessons. Any takers?

**Comment by nhejazi** [comment]
@naupaka - I'd be happy to try sketching out a module based on the material on defensive programming with `stopifnot` that @jdblischak already prepared. Having looked through the lesson structure for the gapminder module, I'm not sure it requires a whole separate lesson but perhaps an additional section within the "Functions Explained" lesson. (I'd submit this as a PR as part of completing the checklist for instructor training.) Nobody is already working on this, right?

**Comment by naupaka** [comment]
@nhejazi Nope, no one is working on it. Thanks for agreeing to take it on!

I agree it would make sense to add into the functions lesson. Doesn't have to be too long -- but great to introduce the idea to people right away when they learn about functions for the first time. Be sure to submit the PR with just the changes to the `.Rmd` (we don't need the `.md`).

**Comment by nhejazi** [comment]
Thanks for the quick input. I've gone ahead and adapted parts of the material from the original lesson and integrated it with the lesson on functions. The PR noted above is the result of this work. I think the PR could still use some work before being merged -- in particular, I feel that the introduction to defensive programming is a bit of an aside, but I included it rather early in the lesson in order to ensure that the examples could be simple (otherwise, I fear that adapting later examples from the lesson would lead to needless distraction from the point of using assertion guards like `stopifnot`). I'd be happy to amend the PR based on any input.

**Comment by katrinleinweber** [comment]
In case anyone reading this _is_ interested in a uni-test lesson: [TIBHannover.GitHub.io/FAIR-R](https://tibhannover.github.io/FAIR-R/) forks off of r-novice-inflammation after its functions episode and teaches documenting, packaging & testing.
