### ISSUE TITLE
Nitpicky challenges

### ISSUE THREAD

**Issue by marwahaha** [swcarpentry/r-novice-gapminder#252]
Hi folks,

@kevin-vilbig and I ran a workshop using this material last month. We found many of the challenges to be nit-picky and not appropriate for first-time R users. Was this intentional?

A particularly frustrating example: http://swcarpentry.github.io/r-novice-gapminder/03-seeking-help/#challenge-2

Additionally, much of the content in 01-03 does not touch do data manipulation until much later. Our learners felt like this wasn't `useful` and couldn't find a connection to the tasks they would be doing. It's a lot of content (and language details!) right at the beginning, without much explanation on "why this is useful".

**Comment by naupaka** [comment]
Hi @marwahaha - thanks for the feedback. In my personal experience, it is up to instructors to decide which, if any, of the challenges or lessons they choose to include when they teach, depending on how deep they want to dive into any particular aspects of learning R. I think instructors should feel empowered to use and structure the material as they see fit for any given workshop - in my own teaching, I certainly think of the materials as a menu or a palette of things to draw from, instead of a strict script to go through. 

Many decide to change up the order that they teach the various episodes to better fit their own instincts on how to get through the material. 

If you have a specific proposal as to how the flow of the material should be restructured, please do add it as an issue for the rest of the community to discuss. I think there are definitely good arguments for moving some of the sections about data types and so forth later in the flow of things, but other good reasons for keeping them near the front. 

I just taught a workshop last weekend, and one of the comments we got was that students would have preferred some of the specific language details even earlier (we led with reading in data and plotting). So I think YMMV, based on the audience and the way the rest of the workshop overall is structured.

**Comment by naupaka** [comment]
Closing this for now, but please feel free to resubmit a new issue or pull request if you have specific changes you'd like to propose.
