### ISSUE TITLE
Project Management With RStudio: Git

### ISSUE THREAD

**Issue by kekoziar** [swcarpentry/r-novice-gapminder#275]
One of the objectives of this episode is to use git from within RStudio, but there is no indication in the setup for the lesson that git should be installed, and it does not install automatically with R or RStudio.  If git is part of the lesson, installation and configuration should be required as part of the setup.  Perhaps the git parts of the lesson can be indicated as optional, with the setup having the same indication along with the link to git installation instructions?

**Comment by naupaka** [comment]
I agree that this is a problem. 

I think it potentially makes sense to remove that git section altogether, since it is cursory and doesn't have the necessary background included. Plus, there is a far better version of this content [over in the git-novice lessons](http://swcarpentry.github.io/git-novice/14-supplemental-rstudio/). We could just link to that.

My inclination would be to remove that whole section in that episode and just link out to the other content as a callout. What do you think @kekoziar?

**Comment by kekoziar** [comment]
I agree that linking to other content would be a good solution.  I like the challenge associated with git, so I will can put an issue in at the git-novice lesson to add the challenge to their page.

**Comment by naupaka** [comment]
Would you also be willing to submit a PR on this repo removing the current git content and adding that link?

**Comment by kekoziar** [comment]
Yes.

**Comment by naupaka** [comment]
@kekoziar still willing to submit that PR?

**Comment by kekoziar** [comment]
@naupaka Yes.  Sorry, for the delay; I've been traveling for a bit.

**Comment by naupaka** [comment]
Closed by #291
