### ISSUE TITLE
ep11 (writing data) - format & content issue in challenge 1

### ISSUE THREAD

**Issue by mfoos** [swcarpentry/r-novice-gapminder#314]
In the "Saving Plots" exercise, Challenge 1, there is a formatting error that is making "> >" appear where the authors intend a blank line inside a block quote, and in that same block, the instructions say to "create a second page" but the solution only outputs one page (p is assigned and a modified version is printed, but p itself is not printed).

**Comment by naupaka** [comment]
Thanks for logging the issue, @mfoos! Good catch. I think that the "> >" issue is a problem with the CSS template we're using. As far as I can tell, wherever else we have a challenge answer, there are no blank lines. 

So that could either be solved by deleting those blank lines altogether, or else putting each part of the solution into its own code chunk ([like here](https://github.com/swcarpentry/r-novice-gapminder/blame/gh-pages/_episodes_rmd/06-data-subsetting.Rmd#L179)).

The second thing you mention (that the solution isn't actually a complete solution) should be corrected too. Should be easy to fix by adding in a call to `p` on the line before the `p + facet_wrap()`

Want to take a crack at a PR to fix those?

**Comment by naupaka** [comment]
@rgaiacs -- any thoughts on where the fix would have to be applied to deal with the blank line in the challenge solution block CSS/md problem?

**Comment by rgaiacs** [comment]
If you look at https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes/11-writing-data.md you will find

~~~
> ## Challenge 1
>
> Rewrite your 'pdf' command to print a second
> page in the pdf, showing a facet plot (hint: use `facet_grid`)
> of the same data with one panel per continent.
> > ## Solution to challenge 1
> >
> > 
> > ~~~
> > pdf("Life_Exp_vs_time.pdf", width = 12, height = 4)
> > > >
> > p <- ggplot(data = gapminder, aes(x = year, y = lifeExp, colour = country)) +
> >   geom_line() +
> >   theme(legend.position = "none")
> > > >
> > p + facet_grid(. ~continent)
> > > >
> > dev.off()
> > ~~~
> > {: .r}
> {: .solution}
{: .challenge}
~~~

This chunk should be

~~~
> ## Challenge 1
>
> Rewrite your 'pdf' command to print a second
> page in the pdf, showing a facet plot (hint: use `facet_grid`)
> of the same data with one panel per continent.
> > ## Solution to challenge 1
> >
> > 
> > ~~~
> > pdf("Life_Exp_vs_time.pdf", width = 12, height = 4)
> > 
> > p <- ggplot(data = gapminder, aes(x = year, y = lifeExp, colour = country)) +
> >   geom_line() +
> >   theme(legend.position = "none")
> > 
> > p + facet_grid(. ~continent)
> > 
> > dev.off()
> > ~~~
> > {: .r}
> {: .solution}
{: .challenge}
~~~

The problem isn't with the CSS as @naupaka suggested but with the Markdown itself. Because the Markdown file is being generated by [bin/generate_md_episodes.R](https://github.com/swcarpentry/r-novice-gapminder/blob/gh-pages/bin/generate_md_episodes.R) which requires [bin/chunk-options.R](https://github.com/swcarpentry/r-novice-gapminder/blob/gh-pages/bin/chunk-options.R) my hypothesis is that the issue is with the [knitr](https://yihui.name/knitr/).

# Minimal Reproducible Example

~~~
---
title: Writing Data
output:
  md_document:
    variant: markdown
---

```{r, include=FALSE}
source("../bin/chunk-options.R")
```

> ## Challenge 1
>
> Rewrite your 'pdf' command to print a second
> page in the pdf, showing a facet plot (hint: use `facet_grid`)
> of the same data with one panel per continent.
> > ## Solution to challenge 1
> >
> > ```{r, eval = FALSE}
> > x <- 2
> >
> > x <- x + 1
> >
> > x <- x + 1
> > ```
> {: .solution}
{: .challenge}
~~~

# Default Knitr call

~~~
---
output:
  md_document:
    variant: markdown
title: Writing Data
---

> Challenge 1
> -----------
>
> Rewrite your 'pdf' command to print a second page in the pdf, showing
> a facet plot (hint: use `facet_grid`) of the same data with one panel
> per continent. &gt; \#\# Solution to challenge 1 &gt; &gt; &gt; ~\~~
> &gt; x &lt;- 2 &gt; &gt; &gt; &gt; x &lt;- x + 1 &gt; &gt; &gt; &gt; x
> &lt;- x + 1 &gt; ~\~~ &gt; {: .r} {: .solution} {: .challenge}
~~~

# Our custom Knitr call

~~~
$ ./bin/knit_lessons.sh _episodes_rmd/mwe.Rmd
~~~

returns

~~~
---
title: Writing Data
output:
  md_document:
    variant: markdown
---



> ## Challenge 1
>
> Rewrite your 'pdf' command to print a second
> page in the pdf, showing a facet plot (hint: use `facet_grid`)
> of the same data with one panel per continent.
> > ## Solution to challenge 1
> >
> > 
> > ~~~
> > x <- 2
> > > >
> > x <- x + 1
> > > >
> > x <- x + 1
> > ~~~
> > {: .r}
> {: .solution}
{: .challenge}
~~~

The execution log says

~~~
processing file: _episodes_rmd/mwe.Rmd
  |.............                                                    |  20%
  ordinary text without R code

  |..........................                                       |  40%
label: unnamed-chunk-1 (with options) 
List of 1
 $ include: logi FALSE

  |.......................................                          |  60%
  ordinary text without R code

  |....................................................             |  80%
label: unnamed-chunk-2 (with options) 
List of 2
 $ eval  : logi FALSE
 $ indent: chr "> > "

  |.................................................................| 100%
  ordinary text without R code


output file: _episodes/mwe.md
~~~

I couldn't dig more.

**Comment by rgaiacs** [comment]
Reported upstream: https://github.com/yihui/knitr/issues/1446.

@naupaka My suggestion is to manual edit the Markdown until we have a upstream solution.

**Comment by mfoos** [comment]
@naupaka currently traveling/overextended, but would be happy to make a PR in the next week or so - I will fix the unprinted p, and it sounds like the stop-gap here is to just remove the "blank" lines in the Markdown?

**Comment by naupaka** [comment]
@mfoos of course, no rush. Yes, I think that's the easiest fix at the moment.

**Comment by rgaiacs** [comment]
@naupaka and @swcarpentry/r-maintainers, Yihui Xie fixed the issue upstream. So if you install knitr from https://github.com/yihui/knitr/ and rebuild the Markdown file it should be good. I really don't remember how you are managing the conversion from R Markdown to Markdown so you might want to inform authors that they need a development version to not have the bug reported here in their Markdown files.

**Comment by naupaka** [comment]
@rgaiacs maintainers do the knitting locally, so it's enough for us to know to use the dev version of knitr - no need for contributors to worry about it. Thanks for helping to get this fixed in knitr!
