### ISSUE TITLE
getwd() introduction

### ISSUE THREAD

**Issue by rlowd** [swcarpentry/r-novice-gapminder#332]
Understanding "where you are" in the system file structure is an important aspect of managing your workflow in R. `getwd()` is a useful function to quickly learn where you are in your file structure. As a helper for a recent workshop, not teaching `getwd()` felt like a gap, and I taught it to a few students in the course of troubleshooting reading in data files in later lessons. 

Additionally, teaching both `getwd()` and the "Go to Working Directory" button on the Rstudio GUI may help students make connections between the unix `pwd` and `cd` commands and navigating Rstudio. 

I would suggest including `getwd()` and the "go to Working Directory" as a part of the "Managing Your Environment" section of the rstudio-intro lesson.

<img width="631" alt="getwd" src="https://user-images.githubusercontent.com/10186179/34121552-0e0c1096-e3ef-11e7-9290-ab4a3a5cddc2.png">

**Comment by naupaka** [comment]
Hi @rlowd thanks for the comment. I agree that's an important thing to cover and isn't included explicitly anywhere as far as I can tell. The way we currenty have the lessons set up, it's not necessary to worry about the working directory too much, though, since it is set automatically in RStudio when you use projects (see [this recent tidyverse post](https://www.tidyverse.org/articles/2017/12/workflow-vs-script/) for rationale). I workshops I've taught the most common reason for confusion is when learners forget to create a new project to work in.

I think it could be useful to explicitly mention `getwd()` and `setwd()` in the second lesson ("02-project-intro") – I think of working directory as more related to project organization than environment management.

 I'd be happy to look over a PR adding in this content to the 2nd episode if you'd be willing to put one together.
