### ISSUE TITLE
Update keyboard key references with Carpentries style

### ISSUE THREAD

**Issue by jcoliver** [swcarpentry/r-novice-gapminder#342]
Some episodes (especial 1 & 2) could use updating to change references to keyboard keys, such as SHIFT and CTRL to conform to Carpentry Style (`<kbd>Shift</kbd>` and `<kbd>Ctrl</kbd>`, respectively). See the [style guide](http://swcarpentry.github.io/lesson-example/06-style-guide/index.html) for more details.

**Comment by jcoliver** [comment]
@naupaka This is a `newcomer-friendly` issue, but I think I lack permissions to apply labels.

**Comment by norcalbiostat** [comment]
I don't think I did it right. I can't compare to the master branch (as requested by the contributing instructions), and I only changed this one file - yet it's saying I want to merge 5 commits (4 of which were from 2 years ago from another person). 
This contribution is surely newcomer friendly, but the instructions on how to correctly do a PR is not newbie-to-git friendly :(

**Comment by norcalbiostat** [comment]
and this fix was merged an hour ago by someone else (since mine didn't work I guess). Can someone close this now? This is the second issue that i've tried to fix that has already been addressed.  Is there some guidance for contributors to at least state that they're working on an issue so others don't waste time trying to fix something that someone else has already done?

**Comment by naupaka** [comment]
@norcalbiostat Thank you for your PR! I'm very sorry it got confusing (I agree git is pretty far from intuitive!). One of the things we are working on this quarter is a more Carpentry-oriented guide for making contributions, in addition to the general guides out there on the Internet.

I think the issue causing the merge conflicts is that you had forked the lesson a while back, and the version you made changes to was an old one instead of the newest, which is why you saw all the merge conflicts. To get the newest changes from this repo, there are two options (and forgive me if you know all of this already, but just in case I'll talk it out):

1) before you make any updates of your own, in your local copy of your forked version of this repository, on your computer:

```sh
# This adds the address to the main SWC repo of the lessons
git remote add upstream https://github.com/swcarpentry/r-novice-gapminder.git

# this checks out the gh-pages branch locally on your machine so changes we pull down
# get added to it (instead of, e.g., the master branch)
git checkout gh-pages

# this pull down all the new changes from the SWC repo and merges them on top of your
# local changes
git pull upstream gh-pages

# this pushes all the updated content back to your fork of the repo, which is 
# under your account on GitHub
git push origin gh-pages
```
Now you have all of the newest changes both locally and on your fork.

Here's a visual:

![github_contribution_workflow](https://user-images.githubusercontent.com/1428071/35473330-bb8be350-0333-11e8-9301-c188cb190ab5.png)

Or, 2) delete your fork on GitHub and then re-fork it, so you have a copy of all the newest changes. Then make your change as usual and open a PR.

Then any time you want to make a new contribution to the repo, just repeat steps 3-6.

Also, I think the documentation is out-of-date, since we just use the gh-pages branch directly now, and don't ever use the master branch. So thank you for pointing that out, we'll need to get that fixed ASAP.

I was also in the middle of fixing the merge conflicts on your PR locally so that your contribution could be merged and your contribution recognized, and was also surprised to see the other PR with a fix to the same issue submitted and merged before yours.  

That's a coordination issue that we (cc: @jcoliver @mawds) as maintainers of this repository need to get figured out (it's just been me for a while, and two new maintainers just started yesterday), and not the way things should work around here. 

Once again, I'm sorry for the confusion and frustration, and I hope it doesn't discourage you from making future contributions! We're also always happy to help troubleshoot the contribution submission process anytime in an issue or a PR -- just tag one or all of us and we can take a look and help get things on track.

**Comment by jcoliver** [comment]
@naupaka Great visualization. Should be connected to #304 !

**Comment by nick-ulle** [comment]
Has this issue been resolved already? Grepping around the repository, I couldn't find any episodes with keyboard shortcuts missing `<kbd>` tags.

**Comment by jcoliver** [comment]
Thanks, @nick-ulle. With one exception, it looks like it (There's an "Esc" in episode 1 that's missing the <kdb> tags).

**Comment by jcoliver** [comment]
This looks to be largely resolved, but please feel free to submmit a pull request as warranted.
