### ISSUE TITLE
stand-alone lessons

### ISSUE THREAD

**Issue by AtiSal** [swcarpentry/r-novice-gapminder#369]
"Exploring Data Frames" lesson starts with the "cat" data frame which is created in the previous lesson, that is, "Data Structures". This might be confusing for learners who already have some knowledge on the data structures and wish to start their training from "Exploring Data Frames". There is no explanation on what "cat" is and if they type "cat" they will simply get an error message as they are not aware of that fact that "cat" was already created in the previous lesson.

An easy fix is to create "cat" data frame in this lesson as well, or provide information on the the variables learners need to create (prerequisites) before proceeding to the lesson. 

Thanks, 
Ati

**Comment by mawds** [comment]
Hi Ati,

Thanks for the suggestion.   You're right that the "cats" data comes out of nowhere if the episode is looked at in isolation

We're wondering whether to replace the "cat" example in this episode with a small subset of the gapminder data (see issue  #356), which will, I think, resolve this issue.    I'll leave the issue open for now so that we can revisit if we decide not to go down this route.

**Comment by raynamharris** [comment]
Alternatively, a short disclaimer could be added at the top and the reader could be prompted to load the cats data quickly with:

```
cats <- data.frame(coat = factor(c("calico", "black", "tabby")),
                   weight = c(2.1, 5.0, 3.2),
                   likes_string = c(1, 0, 1))
```

**Comment by jcoliver** [comment]
We are making significant revisions to episodes 4 and 5 in response to changes introduced by R 4.0. Please feel free to re-open as warranted.
