### ISSUE TITLE
Use of swc-releases

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#405]
All the links from http://swcarpentry.github.io/r-novice-gapminder/ are pointing users to content in http://swcarpentry.github.io/swc-releases/2016.06/r-novice-gapminder/ instead of http://swcarpentry.github.io/r-novice-gapminder/.

**Comment by raynamharris** [comment]
I noticed this too! While it makes navigating a little harder, does this mean you can access any version of the lessons?

**Comment by jcoliver** [comment]
Thanks @rgaiacs and @raynamharris . This warrants inspection. @naupaka do you know why this is? Is there a resource that explains the releases and infrastructure/syntax?

**Comment by naupaka** [comment]
I am surprised it doesn't go to a more recent lesson release (I think they did one in 2018.06)? That is probably a bug. 

However, my recollection is that the pointer to the release version instead of the plain GitHub version is intentional, which helps mitigate the fact that we don't use a development branch. People felt that it was hard to have the lessons changing at any time, sometimes even within a workshop, where an instructor who printed out the lessons the night before and the lessons on the site on the day of could be significantly different and mess things up. @fmichonneau I imagine the links should be updated to a more recent release?

**Comment by rgaiacs** [comment]
> However, my recollection is that the pointer to the release version instead of the plain GitHub version is intentional

But this is the only lesson with this behaviour.

**Comment by jcoliver** [comment]
Not fixed by #426 . But we should decide whether we are keeping the current behavior (referencing a specific release) or changing to that of other lessons (references are to whatever is on the `gh-pages` branch on the GitHub repo).

**Comment by naupaka** [comment]
I think it's working now?

Links seem to work, http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/index.html is up-to-date and pointing to gh-pages version.

**Comment by naupaka** [comment]
I think it probably was that wayward index.html file...

**Comment by fmichonneau** [comment]
It seems that GitHub hadn't rebuilt the website yet. Please ping me again if it's still broken.

**Comment by rgaiacs** [comment]
Thanks!!!
