### ISSUE TITLE
"~/Desktop" for setwd() isn't the OS standard Desktop in Windows

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/r-novice-gapminder#435]
As mentioned in https://carpentries.topicbox.com/groups/discuss/Tdeb023c3d8873d39-M4f43fa22d3ee362bf2d9fca9/r-setwd-desktop-in-windows and confirmed by Ashwin Srinath and Pariksheet Nanda, the use of

```
setwd("~/Desktop")
```

in Windows, can send users to one folder that isn't one Desktop folder that isn't the same as the one they normally see.

We should add a note to this on the Instructors Note or a call out box on the lesson itself (when we introduce `setwd()`, see https://github.com/swcarpentry/r-novice-gapminder/issues/332).

**Comment by psolymos** [comment]
This is related to how R defines home folder after tilde expansion. On Windows it is `C://Users//Foo//Documents//` instead of ``C://Users//Foo//`. You can put something like this in `etc/Rprofile.site`:

```
if (.Platform$OS.type == "windows") {
    Sys.setenv(R_USER="C://Users//Foo//")
    setwd("~")
}
```

although this has a side effect when calling R from a directory, or using an R project in Rstudio -- you'll still end up in `C://Users//Foo//`.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
