### ISSUE TITLE
Use read_... functions rather than read.csv, read.table etc

### ISSUE THREAD

**Issue by markdunning** [swcarpentry/r-novice-gapminder#442]
Hi,

It seems like read_csv, read_tsv et al are the tidyverse way of importing data frames, but in some of the lessons (ggplot2, dplyr in particular) read.csv is used. Perhaps time to switch to using `read_csv`?

**Comment by mawds** [comment]
Good comment; potentially this is quite a big change, if we move over to "pure" tidyverse throughout.  @naupaka @jcoliver ; what are your thoughts?  

FWIW I think we should at some point end up switching to a pure tidyverse approach, as it becomes more widely used.   Whether that is now or not I'm less sure.  Presumably a change of that size is something the curriculum advisory committee would want to take a view on?

**Comment by naupaka** [comment]
I agree this is a question for the advisory committee. Personally I would be inclined to switch all to base R's `read.csv()` for these lessons, as I am not sure the benefit to the specific things we are covering. Not because the tidyverse isn't great, but advocating for dependencies right off the bat makes me a little nervous.

**Comment by EspenRosenquist** [comment]
I agree with @naupaka. It is best to use base functions where they are just as simple to use or where the readr:: version adds no benefits (that I know of). On the contrary, having direct control of the `encoding` parameter is much more convenient than `locale` in the `readr` package. Especially for R users on Windows or otherwise having to read non `UTF-8`data (or forcing said encoding) data.

**Comment by pschloss** [comment]
The #1 reason to scrap the `read.XXX` functions is that it automatically converts strings to factors. `read_XXX` does not. IMHO, there's no reason a learner needs to hear the word "factor" in a SWC workshop.

**Comment by jcoliver** [comment]
Given updates to R 4.0, `read.csv()` no longer reads in strings as factors by default.
