### ISSUE TITLE
[Suggestion] Replace the read.csv(data/gapminder.csv) with library(gapminder)

### ISSUE THREAD

**Issue by anuj2054** [swcarpentry/r-novice-gapminder#481]
Since gapminder dataset also exist as R package, it might be easier to ask students to install that package and use the dataset just like we would use an iris dataset.

Students have already had experience creating and reading in CSV files in episode 4 with the cats and feline data, so I dont think showing them how to read in CSV files is the point here.

So using this package removes the confusion of having to find the data in the SWC website etc for the students.

```
install.packages("gapminder")
library(gapminder)
View(gapminder)
```

**Comment by naupaka** [comment]
Worth considering! In general I think learners are more likely to have to read in data from csv files than getting their data from packages, but I could potentially be convinced otherwise. Thoughts, @mawds @jcoliver ?

**Comment by jcoliver** [comment]
I agree with @naupaka . While loading in the data from the gapminder package is easier, I do think the reinforcing `read.csv` through multiple examples is important for our learners, since they will, for the most part, not be dealing with pre-loaded data sets in their own work.

**Comment by wallacelab** [comment]
I'm in favor of the original poster and using library(gapminder), especially in lessons where reading/writing CSV isn't a major focus (such as the ggplot2 lesson). An independent workshop I ran ~6 months ago ground to a halt for 30+ minutes as more than half the class couldn't locate the download link. (Part of this was on the instructor not preparing sufficiently; nonetheless, if I had known about the gapminder library at the time it would have saved a ton of time and lots of grief for the learners.)

At the very least, I would recommend including a note at the beginning of the lessons using gapminder data to the effect of "If the instructor thinks it is appropriate, the gapminder data can also be loaded as an R library using `library(gapminder)`. This is faster and less error-prone, but does mean learners get less reinforcement of how to read in CSV files. The instructor can decide which method will best serve their particular learners."

**Comment by Athanasiamo** [comment]
I'm in favour of keeping the lesson to reading in the csv. If learners cannot even locate the csv file, while not integral part of the R lesson, it is an integral part of even working with R for one self. While it might be making the pace slow for the learners that are comfortable navigating their computer, if the learners that are not cannot after the lesson open their own data in R, they will not continue using the tool. I have colleagues who struggle with this, and said that when they did a small workshop of mine with the gapminder package was the first time they managed to get data into R. But that is not the standard way of getting data into R, so it will not help them getting started on their own.

I guess in the end, it depends on what you want to focus on. Getting on with the lesson (using gapminder package for the data), or teaching the learners how to get data into R using a conventional approach they may later apply on their own data. Repetition really does help people remember what they should be doing. 

I'd say it would be more important to find ways that make it easier for the learners to find the data on the SWC webpage, rather than changing the way the data is read. For instance by more effectively using etherpad or other ways of easily sharing direct download links.

**Comment by naupaka** [comment]
I think this is a key comment by @Athanasiamo --

> I'd say it would be more important to find ways that make it easier for the learners to find the data on the SWC webpage, rather than changing the way the data is read.

**Comment by joseandresmontes** [comment]
I am commenting as part of the checkout process and came across this interesting conversation. As someone that has been a learner, a helper (and hopefully soon) an instructor, I second @Athanasiamo. I think that keeping with the read.csv helps with the reinforcement of a practice that new learners will find helpful. However, I would encourage instructors to use the library as a backup in the case they are limited in how many helpers/instructors are available to help individuals struggling in the workshop. Like @wallacelab shared, I have been in a workshop where too many people were having trouble and we were limited available helpers (which cuts on time covering other areas). Overall, I hope that data sets or other files are made somehow more accessible from the carpentry website (since I initially struggled to find data and figure others who are not as motivated might not want to bother digging deeper like I did).

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
