### ISSUE TITLE
Subscript and superscript formatting not rendered correctly

### ISSUE THREAD

**Issue by jcoliver** [swcarpentry/r-novice-gapminder#565]
In the knitr lesson (episode 15), subscripts and superscripts are not rendered correctly online. This is due to a dependency on MathJax that is not part of the Carpentries template (see discussion at [https://github.com/carpentries/styles/issues/154](https://github.com/carpentries/styles/issues/154)). One possible workaround is to include MathJax via the YAML header for the specific episode. i.e. for episode 15, we could add:

```
require_mathjax: true
```

to the YAML header. This may precipitate challenges when Carpentries styles are updated. Maybe. Any thoughts, @naupaka ?

See also discussion in #564 .

**Comment by naupaka** [comment]
Hmmmm. Seems like the easy fix for now is to add this to the header, but then things might break in the future. I'm probably a +1 for adding to the YAML, but I also feel like this is a little above my pay grade since it's more a question for the style folks. Naive question: normal html [sup](https://www.w3schools.com/tags/tag_sup.asp) and [sub](https://www.w3schools.com/tags/tag_sub.asp) tags don't work?

**Comment by jcoliver** [comment]
I suspect `<sup>` and `<sub>` will work, but immediately succeeding the sub/superscript section is an example of LaTeX math formula formatting, which is also not rendered correctly. I imagine one _could_ use html tags to render a formula, but that terrifies me. Stay tuned for more input from the style gurus.

**Comment by jcoliver** [comment]
Closing this for now, but please feel free to submit a pull request if time and resources afford.
