### ISSUE TITLE
Major HTML rendering errors in multiple episodes

### ISSUE THREAD

**Issue by marklcrowe** [swcarpentry/r-novice-gapminder#746]
Hi, there is something causing major rendering errors in the episode 13 markdown file. I think it might be a rogue space in line 151 (between > and ```) but I'm not sure. Whatever it is, it's making that page largely unusable - please can you see if you can track down what it might be? Thanks

**Comment by marklcrowe** [comment]
Also looks like a similar bug has affected episodes 1, 6, and 7. In all cases, it's something within the formatting code for the challenges that's causing the problem.

**Comment by zkamvar** [comment]
For full clarification: this happened because [knitr 1.35 introduced a new rule where the opening and closing code fences must have the same indentation](https://github.com/yihui/knitr/releases/tag/v1.35). This was introduced to [allow for code with backtics to be included in knitr chunks](https://github.com/yihui/knitr/issues/1621). 

The behavior is now [downgraded to a warning in knitr 1.36](https://github.com/yihui/knitr/releases/tag/v1.36).

I know I sound like a broken record, but things like this will not be an issue in the new infrastructure, which is nearing beta.
