### ISSUE TITLE
Suggestions for Introduction to R and RStudio - Work Flow within RStudio

### ISSUE THREAD

**Issue by bdezray** [swcarpentry/r-novice-gapminder#758]
The space between Work and flow in the title of the [Work flow within RStudio](https://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/index.html#work-flow-within-rstudio) chunk should be removed as workflow is a single word. 

Also, in this same section, reference to a .R file occurs without explanation that this is reflective of the R scripts described above. This could potentially be fixed by changing the first way to work within RStudio to: Test and play within the interactive R console then copy code into a R script(.R file) to run later.

**Comment by jcoliver** [comment]
Thanks, @bdezray . The change to "workflow" would be a fairly straightforward fix - want to submit a PR?

For a more explicit introduction to the .R file, I think adding another line, explaining that R scripts have the .R file extension would be sufficient. This could immediately follow "Once you open files, such as R scripts, an editor panel will also open in the top left."

**Comment by Hanson19** [comment]
I noticed that in the lesson you don't really highlight many of advantages of R studio in regards to the environmental panel and such. R studio helps make the learning curve to use R a little less difficult because it provides some form of a click/interactive environment which I think for learners who really only analyzed data through something like excel is helpful. 
I think there are just small moments in your lesson where you can highlight these features such as in your "Variables and assignments" section where you assign a value to an object called x. I think after that you should bring attention that now in the environment tab you can see an object called x there.

**Comment by XAM12** [comment]
I just came to this page to create an improvement for the get-involved activity. As far as I reviewed the [lessions page](https://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro.html#workflow-within-rstudio), the concerns from the first two posts (spelling error in worksflow and explanation of file extension for R scripts) have both already been addressed in commits by @longr.  So from my point of view, the issue can be closed and should no longer be listed on the [Help Wanted page](https://carpentries.org/lessons/help_wanted/)

**Comment by skanwal** [comment]
Thanks @XAM12 - I agree we can close this issue as the initial points have been addressed.
