### ISSUE TITLE
Lesson 4: Data Structures: factor is not a data structure

### ISSUE THREAD

**Issue by jcoliver** [swcarpentry/r-novice-gapminder#86]
Under 'Data Structures' heading, factor is listed as a data structure, but factor is a data type.

**Comment by widdowquinn** [comment]
So far as teaching the way that factors are used in `R` is concerned, I don't see the technical difference between "data type" and "data structure" being a major sticking point - I'm not sure novice learners worry about the difference. 

I would have considered a factor to be composed of the `numeric` (specifically, `integer`) and `character` data types and, as it is a specific implementation of in `R`, I'd consider it a data structure (labelled `integer`), rather than an abstract data type.

Would I be wrong?

**Comment by naupaka** [comment]
I was with @jcoliver when he added the issue, and I think it's a reasonable point of confusion (I've always thought of a factor as a type instead of a structure), plus I've seen it both ways in online lists of "data types in R". But, according to R, it looks like you're right @widdowquinn:

```
> typeof(c("a", "a", "b"))
[1] "character"
> typeof(factor(c("a", "a", "b")))
[1] "integer"
> str(c("a", "a", "b"))
 chr [1:3] "a" "a" "b"
> str(factor(c("a", "a", "b")))
 Factor w/ 2 levels "a","b": 1 1 2
```

So perhaps should be left as-is. And I will update my thinking on factors!
