### ISSUE TITLE
subscripts are actually strikethroughs

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/r-novice-gapminder#861]
### How could the content be improved?

In the [a bit more markdown section](https://swcarpentry.github.io/r-novice-gapminder/15-knitr-markdown.html#a-bit-more-markdown), the instructions on how to do subscripts actually show how to do strikethrough.

### Which part of the content does your suggestion apply to?

https://swcarpentry.github.io/r-novice-gapminder/15-knitr-markdown.html#a-bit-more-markdown

**Comment by zkamvar** [comment]
Note: this was a bug with the transition where the subscripts were converted to strikethrough (see https://github.com/ropensci/tinkr/issues/99), so it can be fixed by converting the text.

https://github.com/swcarpentry/r-novice-gapminder/blame/963788408e08fc29022686797471dc0296ce2405/episodes/15-knitr-markdown.Rmd#L231

**Comment by matthieu-bruneaux** [comment]
Thank you very much for noticing this @maneesha and for suggesting the fix @zkamvar!

Since it was a simple fix I took the liberty of submitting and merging the PR myself.
