### ISSUE TITLE
Introduce recycling rule earlier

### ISSUE THREAD

**Issue by davharris** [swcarpentry/r-novice-gapminder#88]
Right now, the recycling rule is first introduced explicitly in lesson 6, in a section on subsetting, in a subsection on logical operators. Recycling isn't primarily a property of subsetting or logical operations, however, and so my sense is that it could seem like a pretty big digression for the students.  We're asking them to do (somewhat advanced) vector operations for the first time in a very unfamiliar context.

What do the project maintainers think about moving section 9 (vector operations, including the recycling rule) up before the section on subsetting? From what I can tell, section 9 doesn't really depend on sections 6-8, except for one advanced example at the very end that uses a function.

**Comment by gvwilson** [comment]
Any thoughts?

**Comment by naupaka** [comment]
Alternatively the tip callout on recycling could be moved from lesson 6 to lesson 9. Lesson 9 is currently quite short so it could work there. My personal sense is that most people will need to learn to subset data before they need to understand the idea of vectorized operations - I think that's why it was put earlier. But I don't feel super strongly either way.

**Comment by gvwilson** [comment]
If there's no other strong feelings, I vote for closing this one.

**Comment by naupaka** [comment]
Closing for now, but of course always welcome to further ideas on lesson ordering down the road.
