### ISSUE TITLE
Suggestion - Print Statement after Data Frame Manipulation functions 

### ISSUE THREAD

**Issue by sndaba** [swcarpentry/r-novice-gapminder#882]
Hi

I noticed that the functions used in the Data Frame Manipulation with Dplyr episode https://swcarpentry.github.io/r-novice-gapminder/13-dplyr/index.html do not have a _print ( ) statement_ for the output of the dplyr functions.

I suggest adding the print statement for every Dplyr function for learners to follow the different outputs every function creates.
For example,  the following function from the episode can have the following printing statement after the select( ) statement;
year_country_gdp <- select(gapminder, year, country, gdpPercap)
print(year_country_gdp)

or

year_country_gdp <- select(gapminder, year, country, gdpPercap)
year_country_gdp

**Comment by naupaka** [comment]
Thanks for the suggestion! My sense is that generally `print()` statements are used on infrequently in R code, since the output can be checked by simply selecting and running the code of interest. I worry that it might be more confusing to break up the dplyr pipe chains any further. In a number of places in the lesson, the output is visualized using either a direct output of the data frame or the use of `head()` etc.

**Comment by skanwal** [comment]
Closing the issue. Please feel free to reopen if this needs to be re-discussed.
